# Generated by Django 5.2.6 on 2026-06-07 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Session key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Trình duyệt')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Hoạt động cuối')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='Đăng nhập lúc')),
                ('current_page', models.CharField(blank=True, max_length=200, verbose_name='Trang hiện tại')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên đang hoạt động',
                'verbose_name_plural': 'Phiên đang hoạt động',
                'db_table': 'active_session',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VIEW', 'Xem'), ('CREATE', 'Tạo mới'), ('UPDATE', 'Chỉnh sửa'), ('DELETE', 'Xóa'), ('EXPORT', 'Xuất file'), ('IMPORT', 'Nhập file'), ('LOGIN', 'Đăng nhập')], max_length=10, verbose_name='Loại hành động')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Đối tượng')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Tên đối tượng')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký hoạt động',
                'verbose_name_plural': 'Nhật ký hoạt động',
                'db_table': 'user_activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_user_time_idx'), models.Index(fields=['-created_at'], name='activity_time_idx'), models.Index(fields=['model_name'], name='activity_model_idx'), models.Index(fields=['action_type'], name='activity_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('FAILED', 'Đăng nhập thất bại')], default='LOGIN', max_length=10, verbose_name='Hành động')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Trình duyệt / Thiết bị')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session key')),
                ('attempted_username', models.CharField(blank=True, max_length=150, verbose_name='Username (khi thất bại)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử đăng nhập',
                'verbose_name_plural': 'Lịch sử đăng nhập',
                'db_table': 'user_login_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_log_user_time_idx'), models.Index(fields=['-created_at'], name='login_log_time_idx'), models.Index(fields=['action'], name='login_log_action_idx')],
            },
        ),
    ]
