# Generated by Django 5.2.8 on 2026-05-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Họ tên")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Cai", "Cai (Cai quản)"),
                            ("Tho", "Thợ"),
                            ("Phu", "Phụ"),
                        ],
                        max_length=20,
                        verbose_name="Nghề",
                    ),
                ),
                (
                    "daily_wage",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Tiền công (1 ngày)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Nhân viên",
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tăng/Giảm",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tăng giảm lương",
                "verbose_name_plural": "Tăng giảm lương",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày")),
                (
                    "regular_workday",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Công HC",
                    ),
                ),
                (
                    "overtime_workday",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Công TC",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chấm công",
                "verbose_name_plural": "Chấm công",
                "unique_together": {("employee", "date")},
            },
        ),
    ]
