# Generated by Django 5.2.6 on 2026-05-31 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongTrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cong_trinh', models.CharField(max_length=255, verbose_name='tên công trình')),
                ('dia_diem', models.CharField(blank=True, max_length=255, null=True, verbose_name='địa điểm')),
            ],
            options={
                'verbose_name': 'công trình',
                'verbose_name_plural': 'Danh sách công trình',
                'db_table': 'cong_trinh',
            },
        ),
        migrations.CreateModel(
            name='DanhMucNghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nghe', models.CharField(max_length=100, verbose_name='Tên nghề/Chức vụ')),
                ('luong_ngay', models.FloatField(default=0.0, verbose_name='Lương ngày cơ sở (Công HC)')),
            ],
            options={
                'verbose_name': 'Danh mục nghề',
                'verbose_name_plural': 'Danh mục Nghề & Lương',
                'db_table': 'danh_muc_nghe',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
            ],
            options={
                'verbose_name': 'Nhân viên ',
                'verbose_name_plural': 'Danh sách nhân viên',
                'db_table': 'nhan_vien',
            },
        ),
        migrations.CreateModel(
            name='PhuThuThuongPhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_ghi_nhan', models.DateField(verbose_name='Ngày ghi nhận (Thường chốt cuối tuần)')),
                ('so_tien_tang', models.FloatField(default=0.0, verbose_name='Số tiền tăng (Thưởng/Phụ cấp)')),
                ('so_tien_giam', models.FloatField(default=0.0, verbose_name='Số tiền giảm (Phạt/Tạm ứng)')),
                ('cong_trinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_phu_thu', to='payroll.congtrinh')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_phu_thu', to='payroll.nhanvien')),
            ],
            options={
                'verbose_name': 'Thưởng phạt phụ thu',
                'verbose_name_plural': 'Quản lý Tăng/Giảm',
                'db_table': 'phu_thu_thuong_phat',
            },
        ),
        migrations.CreateModel(
            name='ChotLuongThang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang_nam', models.CharField(max_length=7, verbose_name='Tháng Năm (Định dạng YYYY-MM)')),
                ('tong_cong_hc', models.FloatField(default=0.0, verbose_name='Tổng công HC')),
                ('tong_cong_tc', models.FloatField(default=0.0, verbose_name='Tổng công TC')),
                ('tong_tien_luong_goc', models.FloatField(default=0.0, verbose_name='Tổng tiền lương gốc')),
                ('tong_tien_tang', models.FloatField(default=0.0, verbose_name='Tổng thưởng/Tăng')),
                ('tong_tien_giam', models.FloatField(default=0.0, verbose_name='Tổng phạt/Giảm')),
                ('thuc_lanh_thang', models.FloatField(default=0.0, verbose_name='Thực lĩnh tháng')),
                ('trang_thai', models.CharField(choices=[('NHAP', 'Dự thảo (Chưa khóa)'), ('CHOT', 'Đã chốt (Khóa sổ)')], default='NHAP', max_length=10, verbose_name='Trạng thái')),
                ('ngay_chot', models.DateTimeField(auto_now=True, verbose_name='Ngày thực hiện chốt')),
                ('cong_trinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_luong_thang', to='payroll.congtrinh')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_luong_thang', to='payroll.nhanvien')),
            ],
            options={
                'verbose_name': 'Chốt lương tháng',
                'verbose_name_plural': 'Bảng chốt lương tháng',
                'db_table': 'chot_luong_thang',
                'unique_together': {('thang_nam', 'nhan_vien', 'cong_trinh')},
            },
        ),
        migrations.CreateModel(
            name='ChamCongHangNgay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày chấm công')),
                ('so_cong_hc', models.FloatField(default=0.0, verbose_name='Số công Hành Chính')),
                ('so_cong_tc', models.FloatField(default=0.0, verbose_name='Số công Tăng Ca')),
                ('cong_trinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cham_cong', to='payroll.congtrinh')),
                ('nghe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.danhmucnghe', verbose_name='Nghề thực tế ngày này')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cham_cong', to='payroll.nhanvien')),
            ],
            options={
                'verbose_name': 'Chấm công ngày',
                'verbose_name_plural': 'Chấm công hàng ngày',
                'db_table': 'cham_cong_hang_ngay',
                'unique_together': {('nhan_vien', 'ngay', 'cong_trinh')},
            },
        ),
    ]
