# Generated by Django 5.2.6 on 2026-05-31 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_migrate_data_old_to_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Danh sách nhân viên'},
        ),
        migrations.AlterField(
            model_name='chamconghangngay',
            name='so_cong_hc',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Công không được âm'), django.core.validators.MaxValueValidator(1, message='Công HC tối đa 1 ngày')], verbose_name='Số công Hành Chính'),
        ),
        migrations.AlterField(
            model_name='chamconghangngay',
            name='so_cong_tc',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Công TC không được âm'), django.core.validators.MaxValueValidator(1, message='Công TC tối đa 1 ngày')], verbose_name='Số công Tăng Ca'),
        ),
        migrations.AlterField(
            model_name='chotluongthang',
            name='thang_nam',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_format', message='Định dạng phải là YYYY-MM', regex='^\\d{4}-\\d{2}$')], verbose_name='Tháng Năm (Định dạng YYYY-MM)'),
        ),
        migrations.AlterField(
            model_name='chotluongthang',
            name='thuc_lanh_thang',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thực lĩnh tháng'),
        ),
        migrations.AlterField(
            model_name='chotluongthang',
            name='tong_cong_hc',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng công HC'),
        ),
        migrations.AlterField(
            model_name='chotluongthang',
            name='tong_cong_tc',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng công TC'),
        ),
        migrations.AlterField(
            model_name='chotluongthang',
            name='tong_tien_giam',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng phạt/Giảm'),
        ),
        migrations.AlterField(
            model_name='chotluongthang',
            name='tong_tien_luong_goc',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng tiền lương gốc'),
        ),
        migrations.AlterField(
            model_name='chotluongthang',
            name='tong_tien_tang',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng thưởng/Tăng'),
        ),
        migrations.AlterField(
            model_name='congtrinh',
            name='ten_cong_trinh',
            field=models.CharField(max_length=255, unique=True, verbose_name='tên công trình'),
        ),
        migrations.AlterField(
            model_name='danhmucnghe',
            name='luong_ngay',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Lương phải >= 0')], verbose_name='Lương ngày cơ sở (Công HC)'),
        ),
        migrations.AlterField(
            model_name='danhmucnghe',
            name='ten_nghe',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên nghề/Chức vụ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ho_ten',
            field=models.CharField(max_length=100, unique=True, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Số điện thoại phải có 10-11 chữ số', regex='^[0-9]{10,11}$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='phuthuthuongphat',
            name='so_tien_giam',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Số tiền giảm phải >= 0')], verbose_name='Số tiền giảm (Phạt/Tạm ứng)'),
        ),
        migrations.AlterField(
            model_name='phuthuthuongphat',
            name='so_tien_tang',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Số tiền tăng phải >= 0')], verbose_name='Số tiền tăng (Thưởng/Phụ cấp)'),
        ),
        migrations.AddIndex(
            model_name='chamconghangngay',
            index=models.Index(fields=['ngay'], name='cham_cong_h_ngay_30d9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='chamconghangngay',
            index=models.Index(fields=['nhan_vien', 'ngay'], name='cham_cong_h_nhan_vi_96a66e_idx'),
        ),
        migrations.AddIndex(
            model_name='chamconghangngay',
            index=models.Index(fields=['cong_trinh'], name='cham_cong_h_cong_tr_9c3e85_idx'),
        ),
        migrations.AddIndex(
            model_name='chotluongthang',
            index=models.Index(fields=['thang_nam'], name='chot_luong__thang_n_841e81_idx'),
        ),
        migrations.AddIndex(
            model_name='chotluongthang',
            index=models.Index(fields=['nhan_vien'], name='chot_luong__nhan_vi_14c85a_idx'),
        ),
        migrations.AddIndex(
            model_name='phuthuthuongphat',
            index=models.Index(fields=['ngay_ghi_nhan'], name='phu_thu_thu_ngay_gh_5fd4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='phuthuthuongphat',
            index=models.Index(fields=['nhan_vien'], name='phu_thu_thu_nhan_vi_a8a991_idx'),
        ),
    ]
