# Generated by Django 5.2.5 on 2026-06-02 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_add_validators_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='congtrinh',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='congtrinh',
            name='ngay_bat_dau',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AddField(
            model_name='congtrinh',
            name='thoi_han_ket_thuc',
            field=models.DateField(blank=True, null=True, verbose_name='Thời hạn kết thúc'),
        ),
        migrations.AddField(
            model_name='congtrinh',
            name='trang_thai',
            field=models.CharField(choices=[('MOI', 'Mới tạo'), ('DANG_THI_CONG', 'Đang thi công'), ('TAM_DUNG', 'Tạm dừng'), ('HOAN_THANH', 'Hoàn thành')], default='MOI', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='congtrinh',
            name='dia_diem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='congtrinh',
            name='ten_cong_trinh',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên công trình'),
        ),
    ]
