# Generated by Django 6.0.5 on 2026-06-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_congtrinh_mo_ta_congtrinh_ngay_bat_dau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='cong_trinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.congtrinh', verbose_name='Công trình'),
        ),
    ]
