# Generated by Django 5.2.5 on 2026-06-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_adjustmentlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date', 'cong_trinh')},
        ),
    ]
