# Generated by Django 6.0.5 on 2026-06-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Cai', 'Cai (Cai quản)'), ('Tho', 'Thợ'), ('Phu', 'Phụ'), ('ĐN', 'Đội ngũ khác')], max_length=20, verbose_name='Nghề'),
        ),
    ]
