# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TetBonusSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='Mã cấu hình')),
                ('label', models.CharField(max_length=160, verbose_name='Tên mức thưởng')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Số tiền')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
            ],
            options={
                'verbose_name': 'Cấu hình thưởng Tết',
                'verbose_name_plural': 'Cấu hình thưởng Tết',
                'db_table': 'tet_bonus_setting',
                'ordering': ['key'],
            },
        ),
    ]
